(cat<<EOF ;cat /sdcard/uweb/default.hosts)|awk '!s[$0]++'>a.tmp;mv a.tmp /sdcard/uweb/default.hosts
lianmeng.360.cn
appjiagu.com
adm-cnzz.net
alimama.com
ipinyou.com
mct01.com
tanx.com
wrating.com
cpro.baidu.com
pos.baidu.com
share.baidu.com
bcebos.com
e.qq.com
gdt.qq.com
l.qq.com
push.qq.com
beacon.sina.com.cn
mix.sina.com.cn
go.sohu.com
inte.sogou.com
epro.sogou.com
golden1.sogou.com
uranus.sogou.com
inte.sogoucdn.com
lu.sogoucdn.com
theta.sogoucdn.com
ad.xiaomi.com
EOF
